"""Adicionando a coluna quantidadeUn para fardos

Revision ID: 90fe5de9fc9e
Revises: 
Create Date: 2025-07-17 09:24:41.862829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90fe5de9fc9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'all_users', ['idUsuario'])
    op.add_column('produtos', sa.Column('quantidadeUn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'quantidadeUn')
    op.drop_constraint(None, 'all_users', type_='unique')
    # ### end Alembic commands ###
